/*-------------------------------------------------------------------------
 *
 * kwlist_d.h
 *    List of keywords represented as a ScanKeywordList.
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/tools/gen_keywordlist.pl
 *
 *-------------------------------------------------------------------------
 */

#ifndef KWLIST_D_H
#define KWLIST_D_H

#include "parser/kwlookup.h"

static const char ScanKeywords_kw_string[] =
	"abort\0"
	"absolute\0"
	"access\0"
	"account\0"
	"action\0"
	"add\0"
	"admin\0"
	"after\0"
	"aggregate\0"
	"algorithm\0"
	"all\0"
	"also\0"
	"alter\0"
	"always\0"
	"analyse\0"
	"analyze\0"
	"and\0"
	"any\0"
	"app\0"
	"append\0"
	"archive\0"
	"array\0"
	"as\0"
	"asc\0"
	"assertion\0"
	"assignment\0"
	"asymmetric\0"
	"at\0"
	"attribute\0"
	"audit\0"
	"authid\0"
	"authorization\0"
	"auto_increment\0"
	"autoextend\0"
	"automapped\0"
	"backward\0"
	"barrier\0"
	"before\0"
	"begin\0"
	"begin_non_anoyblock\0"
	"between\0"
	"bigint\0"
	"binary\0"
	"binary_double\0"
	"binary_double_infinity\0"
	"binary_double_nan\0"
	"binary_integer\0"
	"bit\0"
	"blanks\0"
	"blob\0"
	"blockchain\0"
	"body\0"
	"boolean\0"
	"both\0"
	"bucketcnt\0"
	"buckets\0"
	"by\0"
	"byteawithoutorder\0"
	"byteawithoutorderwithequal\0"
	"cache\0"
	"call\0"
	"called\0"
	"cancelable\0"
	"cascade\0"
	"cascaded\0"
	"case\0"
	"cast\0"
	"catalog\0"
	"catalog_name\0"
	"chain\0"
	"change\0"
	"char\0"
	"character\0"
	"characteristics\0"
	"characterset\0"
	"charset\0"
	"check\0"
	"checkpoint\0"
	"class\0"
	"class_origin\0"
	"clean\0"
	"client\0"
	"client_master_key\0"
	"client_master_keys\0"
	"clob\0"
	"close\0"
	"cluster\0"
	"coalesce\0"
	"collate\0"
	"collation\0"
	"column\0"
	"column_encryption_key\0"
	"column_encryption_keys\0"
	"column_name\0"
	"columns\0"
	"comment\0"
	"comments\0"
	"commit\0"
	"committed\0"
	"compact\0"
	"compatible_illegal_chars\0"
	"compile\0"
	"complete\0"
	"completion\0"
	"compress\0"
	"concurrently\0"
	"condition\0"
	"configuration\0"
	"connect\0"
	"connection\0"
	"consistent\0"
	"constant\0"
	"constraint\0"
	"constraint_catalog\0"
	"constraint_name\0"
	"constraint_schema\0"
	"constraints\0"
	"content\0"
	"continue\0"
	"contview\0"
	"conversion\0"
	"convert\0"
	"coordinator\0"
	"coordinators\0"
	"copy\0"
	"cost\0"
	"create\0"
	"cross\0"
	"csn\0"
	"csv\0"
	"cube\0"
	"current\0"
	"current_catalog\0"
	"current_date\0"
	"current_role\0"
	"current_schema\0"
	"current_time\0"
	"current_timestamp\0"
	"current_user\0"
	"cursor\0"
	"cursor_name\0"
	"cycle\0"
	"data\0"
	"database\0"
	"datafile\0"
	"datanode\0"
	"datanodes\0"
	"datatype_cl\0"
	"date\0"
	"date_format\0"
	"day\0"
	"day_hour\0"
	"day_minute\0"
	"day_second\0"
	"dbcompatibility\0"
	"deallocate\0"
	"dec\0"
	"decimal\0"
	"declare\0"
	"decode\0"
	"default\0"
	"defaults\0"
	"deferrable\0"
	"deferred\0"
	"definer\0"
	"delete\0"
	"delimiter\0"
	"delimiters\0"
	"delta\0"
	"deltamerge\0"
	"desc\0"
	"deterministic\0"
	"diagnostics\0"
	"dictionary\0"
	"direct\0"
	"directory\0"
	"disable\0"
	"discard\0"
	"disconnect\0"
	"distinct\0"
	"distribute\0"
	"distribution\0"
	"do\0"
	"document\0"
	"domain\0"
	"double\0"
	"drop\0"
	"dumpfile\0"
	"duplicate\0"
	"each\0"
	"elastic\0"
	"else\0"
	"enable\0"
	"enclosed\0"
	"encoding\0"
	"encrypted\0"
	"encrypted_value\0"
	"encryption\0"
	"encryption_type\0"
	"end\0"
	"ends\0"
	"enforced\0"
	"enum\0"
	"eol\0"
	"error\0"
	"errors\0"
	"escape\0"
	"escaped\0"
	"escaping\0"
	"event\0"
	"events\0"
	"every\0"
	"except\0"
	"exchange\0"
	"exclude\0"
	"excluded\0"
	"excluding\0"
	"exclusive\0"
	"execute\0"
	"exists\0"
	"expired\0"
	"explain\0"
	"extension\0"
	"external\0"
	"extract\0"
	"false\0"
	"family\0"
	"fast\0"
	"features\0"
	"fenced\0"
	"fetch\0"
	"fields\0"
	"fileheader\0"
	"fill_missing_fields\0"
	"filler\0"
	"filter\0"
	"first\0"
	"fixed\0"
	"float\0"
	"following\0"
	"follows\0"
	"for\0"
	"force\0"
	"foreign\0"
	"formatter\0"
	"forward\0"
	"freeze\0"
	"from\0"
	"full\0"
	"function\0"
	"functions\0"
	"generated\0"
	"get\0"
	"global\0"
	"grant\0"
	"granted\0"
	"greatest\0"
	"group\0"
	"grouping\0"
	"groupparent\0"
	"handler\0"
	"having\0"
	"hdfsdirectory\0"
	"header\0"
	"hold\0"
	"hour\0"
	"hour_minute\0"
	"hour_second\0"
	"identified\0"
	"identity\0"
	"if\0"
	"ignore\0"
	"ignore_extra_data\0"
	"ilike\0"
	"immediate\0"
	"immutable\0"
	"implicit\0"
	"in\0"
	"include\0"
	"including\0"
	"increment\0"
	"incremental\0"
	"index\0"
	"indexes\0"
	"infile\0"
	"infinite\0"
	"inherit\0"
	"inherits\0"
	"initial\0"
	"initially\0"
	"initrans\0"
	"inline\0"
	"inner\0"
	"inout\0"
	"input\0"
	"insensitive\0"
	"insert\0"
	"instead\0"
	"int\0"
	"integer\0"
	"internal\0"
	"intersect\0"
	"interval\0"
	"into\0"
	"invisible\0"
	"invoker\0"
	"ip\0"
	"is\0"
	"isnull\0"
	"isolation\0"
	"join\0"
	"key\0"
	"key_path\0"
	"key_store\0"
	"kill\0"
	"label\0"
	"language\0"
	"large\0"
	"last\0"
	"lc_collate\0"
	"lc_ctype\0"
	"leading\0"
	"leakproof\0"
	"least\0"
	"left\0"
	"less\0"
	"level\0"
	"like\0"
	"limit\0"
	"lines\0"
	"list\0"
	"listen\0"
	"load\0"
	"local\0"
	"localtime\0"
	"localtimestamp\0"
	"location\0"
	"lock\0"
	"locked\0"
	"log\0"
	"logging\0"
	"login_any\0"
	"login_failure\0"
	"login_success\0"
	"logout\0"
	"loop\0"
	"mapping\0"
	"masking\0"
	"master\0"
	"match\0"
	"matched\0"
	"materialized\0"
	"maxextents\0"
	"maxsize\0"
	"maxtrans\0"
	"maxvalue\0"
	"merge\0"
	"message_text\0"
	"method\0"
	"minextents\0"
	"minus\0"
	"minute\0"
	"minute_second\0"
	"minvalue\0"
	"mode\0"
	"model\0"
	"modify\0"
	"month\0"
	"move\0"
	"movement\0"
	"mysql_errno\0"
	"name\0"
	"names\0"
	"nan\0"
	"national\0"
	"natural\0"
	"nchar\0"
	"next\0"
	"no\0"
	"nocompress\0"
	"nocycle\0"
	"node\0"
	"nologging\0"
	"nomaxvalue\0"
	"nominvalue\0"
	"none\0"
	"not\0"
	"nothing\0"
	"notify\0"
	"notnull\0"
	"novalidate\0"
	"nowait\0"
	"null\0"
	"nullcols\0"
	"nullif\0"
	"nulls\0"
	"number\0"
	"numeric\0"
	"numstr\0"
	"nvarchar\0"
	"nvarchar2\0"
	"nvl\0"
	"object\0"
	"of\0"
	"off\0"
	"offset\0"
	"oids\0"
	"on\0"
	"only\0"
	"operator\0"
	"optimization\0"
	"option\0"
	"optionally\0"
	"options\0"
	"or\0"
	"order\0"
	"out\0"
	"outer\0"
	"outfile\0"
	"over\0"
	"overlaps\0"
	"overlay\0"
	"owned\0"
	"owner\0"
	"package\0"
	"packages\0"
	"parallel_enable\0"
	"parser\0"
	"partial\0"
	"partition\0"
	"partitions\0"
	"passing\0"
	"password\0"
	"pctfree\0"
	"per\0"
	"percent\0"
	"performance\0"
	"perm\0"
	"pipelined\0"
	"placing\0"
	"plan\0"
	"plans\0"
	"policy\0"
	"pool\0"
	"position\0"
	"precedes\0"
	"preceding\0"
	"precision\0"
	"predict\0"
	"preferred\0"
	"prefix\0"
	"prepare\0"
	"prepared\0"
	"preserve\0"
	"primary\0"
	"prior\0"
	"priorer\0"
	"private\0"
	"privilege\0"
	"privileges\0"
	"procedural\0"
	"procedure\0"
	"profile\0"
	"publication\0"
	"publish\0"
	"purge\0"
	"query\0"
	"quote\0"
	"randomized\0"
	"range\0"
	"ratio\0"
	"raw\0"
	"read\0"
	"real\0"
	"reassign\0"
	"rebuild\0"
	"recheck\0"
	"recursive\0"
	"recyclebin\0"
	"redisanyvalue\0"
	"ref\0"
	"references\0"
	"refresh\0"
	"reindex\0"
	"reject\0"
	"relative\0"
	"release\0"
	"reloptions\0"
	"remote\0"
	"remove\0"
	"rename\0"
	"repeat\0"
	"repeatable\0"
	"replace\0"
	"replica\0"
	"reset\0"
	"resize\0"
	"resource\0"
	"restart\0"
	"restrict\0"
	"return\0"
	"returned_sqlstate\0"
	"returning\0"
	"returns\0"
	"reuse\0"
	"revoke\0"
	"right\0"
	"role\0"
	"roles\0"
	"rollback\0"
	"rollup\0"
	"rotate\0"
	"rotation\0"
	"row\0"
	"row_count\0"
	"rownum\0"
	"rows\0"
	"rowtype\0"
	"rule\0"
	"sample\0"
	"savepoint\0"
	"schedule\0"
	"schema\0"
	"schema_name\0"
	"scroll\0"
	"search\0"
	"second\0"
	"security\0"
	"select\0"
	"separator\0"
	"sequence\0"
	"sequences\0"
	"serializable\0"
	"server\0"
	"session\0"
	"session_user\0"
	"set\0"
	"setof\0"
	"sets\0"
	"share\0"
	"shippable\0"
	"show\0"
	"shrink\0"
	"shutdown\0"
	"siblings\0"
	"similar\0"
	"simple\0"
	"size\0"
	"skip\0"
	"slave\0"
	"slice\0"
	"smalldatetime\0"
	"smalldatetime_format\0"
	"smallint\0"
	"snapshot\0"
	"some\0"
	"source\0"
	"space\0"
	"specification\0"
	"spill\0"
	"split\0"
	"sql\0"
	"stable\0"
	"stacked\0"
	"standalone\0"
	"start\0"
	"starting\0"
	"starts\0"
	"statement\0"
	"statement_id\0"
	"statistics\0"
	"stdin\0"
	"stdout\0"
	"storage\0"
	"store\0"
	"stored\0"
	"stratify\0"
	"stream\0"
	"strict\0"
	"strip\0"
	"subclass_origin\0"
	"subpartition\0"
	"subpartitions\0"
	"subscription\0"
	"substring\0"
	"symmetric\0"
	"synonym\0"
	"sys_refcursor\0"
	"sysdate\0"
	"sysid\0"
	"system\0"
	"table\0"
	"table_name\0"
	"tables\0"
	"tablesample\0"
	"tablespace\0"
	"target\0"
	"temp\0"
	"template\0"
	"temporary\0"
	"terminated\0"
	"text\0"
	"than\0"
	"then\0"
	"time\0"
	"time_format\0"
	"timecapsule\0"
	"timestamp\0"
	"timestamp_format\0"
	"timestampdiff\0"
	"tinyint\0"
	"to\0"
	"trailing\0"
	"transaction\0"
	"transform\0"
	"treat\0"
	"trigger\0"
	"trim\0"
	"true\0"
	"truncate\0"
	"trusted\0"
	"tsfield\0"
	"tstag\0"
	"tstime\0"
	"type\0"
	"types\0"
	"unbounded\0"
	"uncommitted\0"
	"unencrypted\0"
	"union\0"
	"unique\0"
	"unknown\0"
	"unlimited\0"
	"unlisten\0"
	"unlock\0"
	"unlogged\0"
	"until\0"
	"unusable\0"
	"update\0"
	"use\0"
	"useeof\0"
	"user\0"
	"using\0"
	"vacuum\0"
	"valid\0"
	"validate\0"
	"validation\0"
	"validator\0"
	"value\0"
	"values\0"
	"varchar\0"
	"varchar2\0"
	"variables\0"
	"variadic\0"
	"varying\0"
	"vcgroup\0"
	"verbose\0"
	"verify\0"
	"version\0"
	"view\0"
	"visible\0"
	"volatile\0"
	"wait\0"
	"warnings\0"
	"weak\0"
	"when\0"
	"where\0"
	"while\0"
	"whitespace\0"
	"window\0"
	"with\0"
	"within\0"
	"without\0"
	"work\0"
	"workload\0"
	"wrapper\0"
	"write\0"
	"xml\0"
	"xmlattributes\0"
	"xmlconcat\0"
	"xmlelement\0"
	"xmlexists\0"
	"xmlforest\0"
	"xmlparse\0"
	"xmlpi\0"
	"xmlroot\0"
	"xmlserialize\0"
	"year\0"
	"year_month\0"
	"yes\0"
	"zone";

static const uint16 ScanKeywords_kw_offsets[] = {
	0,
	6,
	15,
	22,
	30,
	37,
	41,
	47,
	53,
	63,
	73,
	77,
	82,
	88,
	95,
	103,
	111,
	115,
	119,
	123,
	130,
	138,
	144,
	147,
	151,
	161,
	172,
	183,
	186,
	196,
	202,
	209,
	223,
	238,
	249,
	260,
	269,
	277,
	284,
	290,
	310,
	318,
	325,
	332,
	346,
	369,
	387,
	402,
	406,
	413,
	418,
	429,
	434,
	442,
	447,
	457,
	465,
	468,
	486,
	513,
	519,
	524,
	531,
	542,
	550,
	559,
	564,
	569,
	577,
	590,
	596,
	603,
	608,
	618,
	634,
	647,
	655,
	661,
	672,
	678,
	691,
	697,
	704,
	722,
	741,
	746,
	752,
	760,
	769,
	777,
	787,
	794,
	816,
	839,
	851,
	859,
	867,
	876,
	883,
	893,
	901,
	926,
	934,
	943,
	954,
	963,
	976,
	986,
	1000,
	1008,
	1019,
	1030,
	1039,
	1050,
	1069,
	1085,
	1103,
	1115,
	1123,
	1132,
	1141,
	1152,
	1160,
	1172,
	1185,
	1190,
	1195,
	1202,
	1208,
	1212,
	1216,
	1221,
	1229,
	1245,
	1258,
	1271,
	1286,
	1299,
	1317,
	1330,
	1337,
	1349,
	1355,
	1360,
	1369,
	1378,
	1387,
	1397,
	1409,
	1414,
	1426,
	1430,
	1439,
	1450,
	1461,
	1477,
	1488,
	1492,
	1500,
	1508,
	1515,
	1523,
	1532,
	1543,
	1552,
	1560,
	1567,
	1577,
	1588,
	1594,
	1605,
	1610,
	1624,
	1636,
	1647,
	1654,
	1664,
	1672,
	1680,
	1691,
	1700,
	1711,
	1724,
	1727,
	1736,
	1743,
	1750,
	1755,
	1764,
	1774,
	1779,
	1787,
	1792,
	1799,
	1808,
	1817,
	1827,
	1843,
	1854,
	1870,
	1874,
	1879,
	1888,
	1893,
	1897,
	1903,
	1910,
	1917,
	1925,
	1934,
	1940,
	1947,
	1953,
	1960,
	1969,
	1977,
	1986,
	1996,
	2006,
	2014,
	2021,
	2029,
	2037,
	2047,
	2056,
	2064,
	2070,
	2077,
	2082,
	2091,
	2098,
	2104,
	2111,
	2122,
	2142,
	2149,
	2156,
	2162,
	2168,
	2174,
	2184,
	2192,
	2196,
	2202,
	2210,
	2220,
	2228,
	2235,
	2240,
	2245,
	2254,
	2264,
	2274,
	2278,
	2285,
	2291,
	2299,
	2308,
	2314,
	2323,
	2335,
	2343,
	2350,
	2364,
	2371,
	2376,
	2381,
	2393,
	2405,
	2416,
	2425,
	2428,
	2435,
	2453,
	2459,
	2469,
	2479,
	2488,
	2491,
	2499,
	2509,
	2519,
	2531,
	2537,
	2545,
	2552,
	2561,
	2569,
	2578,
	2586,
	2596,
	2605,
	2612,
	2618,
	2624,
	2630,
	2642,
	2649,
	2657,
	2661,
	2669,
	2678,
	2688,
	2697,
	2702,
	2712,
	2720,
	2723,
	2726,
	2733,
	2743,
	2748,
	2752,
	2761,
	2771,
	2776,
	2782,
	2791,
	2797,
	2802,
	2813,
	2822,
	2830,
	2840,
	2846,
	2851,
	2856,
	2862,
	2867,
	2873,
	2879,
	2884,
	2891,
	2896,
	2902,
	2912,
	2927,
	2936,
	2941,
	2948,
	2952,
	2960,
	2970,
	2984,
	2998,
	3005,
	3010,
	3018,
	3026,
	3033,
	3039,
	3047,
	3060,
	3071,
	3079,
	3088,
	3097,
	3103,
	3116,
	3123,
	3134,
	3140,
	3147,
	3161,
	3170,
	3175,
	3181,
	3188,
	3194,
	3199,
	3208,
	3220,
	3225,
	3231,
	3235,
	3244,
	3252,
	3258,
	3263,
	3266,
	3277,
	3285,
	3290,
	3300,
	3311,
	3322,
	3327,
	3331,
	3339,
	3346,
	3354,
	3365,
	3372,
	3377,
	3386,
	3393,
	3399,
	3406,
	3414,
	3421,
	3430,
	3440,
	3444,
	3451,
	3454,
	3458,
	3465,
	3470,
	3473,
	3478,
	3487,
	3500,
	3507,
	3518,
	3526,
	3529,
	3535,
	3539,
	3545,
	3553,
	3558,
	3567,
	3575,
	3581,
	3587,
	3595,
	3604,
	3620,
	3627,
	3635,
	3645,
	3656,
	3664,
	3673,
	3681,
	3685,
	3693,
	3705,
	3710,
	3720,
	3728,
	3733,
	3739,
	3746,
	3751,
	3760,
	3769,
	3779,
	3789,
	3797,
	3807,
	3814,
	3822,
	3831,
	3840,
	3848,
	3854,
	3862,
	3870,
	3880,
	3891,
	3902,
	3912,
	3920,
	3932,
	3940,
	3946,
	3952,
	3958,
	3969,
	3975,
	3981,
	3985,
	3990,
	3995,
	4004,
	4012,
	4020,
	4030,
	4041,
	4055,
	4059,
	4070,
	4078,
	4086,
	4093,
	4102,
	4110,
	4121,
	4128,
	4135,
	4142,
	4149,
	4160,
	4168,
	4176,
	4182,
	4189,
	4198,
	4206,
	4215,
	4222,
	4240,
	4250,
	4258,
	4264,
	4271,
	4277,
	4282,
	4288,
	4297,
	4304,
	4311,
	4320,
	4324,
	4334,
	4341,
	4346,
	4354,
	4359,
	4366,
	4376,
	4385,
	4392,
	4404,
	4411,
	4418,
	4425,
	4434,
	4441,
	4451,
	4460,
	4470,
	4483,
	4490,
	4498,
	4511,
	4515,
	4521,
	4526,
	4532,
	4542,
	4547,
	4554,
	4563,
	4572,
	4580,
	4587,
	4592,
	4597,
	4603,
	4609,
	4623,
	4644,
	4653,
	4662,
	4667,
	4674,
	4680,
	4694,
	4700,
	4706,
	4710,
	4717,
	4725,
	4736,
	4742,
	4751,
	4758,
	4768,
	4781,
	4792,
	4798,
	4805,
	4813,
	4819,
	4826,
	4835,
	4842,
	4849,
	4855,
	4871,
	4884,
	4898,
	4911,
	4921,
	4931,
	4939,
	4953,
	4961,
	4967,
	4974,
	4980,
	4991,
	4998,
	5010,
	5021,
	5028,
	5033,
	5042,
	5052,
	5063,
	5068,
	5073,
	5078,
	5083,
	5095,
	5107,
	5117,
	5134,
	5148,
	5156,
	5159,
	5168,
	5180,
	5190,
	5196,
	5204,
	5209,
	5214,
	5223,
	5231,
	5239,
	5245,
	5252,
	5257,
	5263,
	5273,
	5285,
	5297,
	5303,
	5310,
	5318,
	5328,
	5337,
	5344,
	5353,
	5359,
	5368,
	5375,
	5379,
	5386,
	5391,
	5397,
	5404,
	5410,
	5419,
	5430,
	5440,
	5446,
	5453,
	5461,
	5470,
	5480,
	5489,
	5497,
	5505,
	5513,
	5520,
	5528,
	5533,
	5541,
	5550,
	5555,
	5564,
	5569,
	5574,
	5580,
	5586,
	5597,
	5604,
	5609,
	5616,
	5624,
	5629,
	5638,
	5646,
	5652,
	5656,
	5670,
	5680,
	5691,
	5701,
	5711,
	5720,
	5726,
	5734,
	5747,
	5752,
	5763,
	5767,
};

#define SCANKEYWORDS_NUM_KEYWORDS 691

static int
ScanKeywords_hash_func(const void *key, size_t keylen)
{
	static const int16 h[1383] = {
		753,   32767, 680,   241,   32767, 298,   32767, 530,
		32767, 32767, -23,   32767, 622,   0,     523,   -18,
		344,   658,   32,    -160,  454,   32767, 417,   312,
		-329,  -80,   -370,  769,   0,     402,   886,   32767,
		392,   32767, 32767, -359,  32767, 595,   32767, 249,
		246,   32767, 401,   32767, 32767, -443,  32767, 207,
		566,   234,   842,   -277,  0,     -461,  32767, 539,
		-176,  114,   32767, 32767, 32767, 147,   256,   32767,
		-347,  32767, 357,   -42,   465,   32767, 32767, 909,
		32767, 51,    32767, 32767, 0,     14,    817,   32767,
		0,     32767, 990,   32767, 32767, 31,    0,     187,
		32767, 450,   0,     501,   32767, 55,    0,     395,
		-418,  1966,  32767, -191,  577,   32767, -201,  677,
		0,     32767, 32767, 250,   32767, 0,     0,     0,
		32767, 32767, 259,   32767, 228,   32767, 221,   239,
		-310,  32767, -206,  32767, -343,  32767, -213,  -301,
		92,    338,   -21,   296,   -150,  714,   32767, 235,
		68,    513,   0,     32767, 102,   32767, 343,   32767,
		0,     32767, 32767, 108,   32767, -93,   0,     -834,
		32767, 438,   676,   32767, 32767, -15,   32767, 0,
		606,   408,   32767, -260,  32767, 32767, 120,   664,
		-1000, -225,  32767, 32767, 32767, 669,   0,     0,
		32767, 301,   268,   137,   0,     266,   32767, 0,
		32767, 32767, 32767, 0,     194,   32767, -589,  -101,
		-180,  183,   32767, -273,  90,    624,   0,     32767,
		32767, 70,    633,   420,   -239,  -192,  7,     32767,
		32767, 652,   0,     32767, -394,  538,   433,   -34,
		32767, 32767, 32767, -12,   0,     455,   0,     236,
		-527,  32767, -569,  -225,  32767, 32767, 320,   32767,
		515,   -188,  32767, 674,   32767, -530,  32767, 32767,
		32767, 32767, 349,   670,   32767, 294,   32767, 32767,
		32,    32767, 32767, 32767, 32767, -223,  272,   241,
		-714,  -700,  32767, 211,   280,   32767, 540,   137,
		32767, 32767, 32767, -142,  -116,  32767, 32767, -21,
		32767, 0,     -132,  32767, 32767, 39,    32767, 341,
		0,     273,   486,   32767, 351,   269,   144,   22,
		222,   32767, 32767, 491,   32767, -116,  -295,  32767,
		263,   32767, -92,   -503,  0,     32767, -322,  -279,
		32767, 1301,  -133,  151,   -5,    0,     114,   279,
		497,   32767, -448,  32767, 480,   32767, 142,   -272,
		0,     32767, -259,  32767, 32767, 41,    32767, 487,
		32767, 259,   32767, -267,  203,   -1091, 296,   -105,
		32767, 32767, 32767, 212,   286,   548,   -809,  -403,
		-115,  -835,  266,   297,   32767, 32767, 805,   32767,
		32767, 32767, 32767, 242,   766,   32767, 32767, 32767,
		32767, 32767, 0,     114,   32767, 32767, -86,   32767,
		-298,  32767, 32767, 32767, 720,   -28,   -1022, 650,
		32767, 43,    32767, 606,   1645,  32767, 213,   586,
		550,   32767, 32767, 168,   32767, 0,     0,     -228,
		32767, 32767, -337,  32767, 32767, 51,    32767, -4,
		32767, 547,   32767, 69,    32767, 643,   514,   32767,
		-257,  32767, 32767, 669,   -76,   -732,  0,     32767,
		683,   32767, 312,   498,   186,   448,   54,    113,
		-71,   32767, 32767, 0,     32767, 0,     349,   506,
		0,     663,   32767, 32767, 32767, 32767, 550,   0,
		-1077, 284,   -115,  32767, 32767, 32767, 279,   32767,
		32767, 395,   0,     -48,   483,   280,   32767, 545,
		32767, 431,   32767, 0,     32767, 45,    598,   692,
		594,   32767, 696,   32767, 547,   549,   210,   -167,
		1051,  -28,   359,   633,   44,    539,   32767, 272,
		529,   127,   375,   1390,  -325,  32767, 32767, 1269,
		32767, 32767, 32767, 88,    32767, 1193,  0,     32767,
		558,   32767, 69,    1041,  32767, 32767, 32767, 470,
		311,   32767, 32767, 32767, -818,  141,   0,     32767,
		267,   0,     32767, -372,  0,     32767, 0,     503,
		696,   0,     32767, 604,   -289,  0,     32767, 1221,
		-137,  32767, 549,   -787,  32767, -180,  -64,   272,
		144,   32767, -103,  -486,  737,   32767, -197,  1289,
		510,   107,   494,   -145,  637,   32767, 18,    626,
		193,   32767, 32767, 32767, 32767, 0,     32767, -494,
		32767, 32767, 112,   32767, 32767, 609,   -1,    661,
		-64,   505,   690,   436,   0,     760,   32767, 310,
		0,     -78,   358,   32767, 32767, 32767, -303,  328,
		152,   153,   670,   -484,  196,   586,   0,     32767,
		32767, 334,   265,   32767, -62,   -1304, 368,   0,
		156,   32767, 0,     32767, 32767, 32767, 61,    0,
		-454,  429,   32767, 32767, 32767, 466,   388,   32767,
		-291,  32767, 32767, 32767, 321,   0,     337,   32767,
		156,   528,   80,    32767, 447,   340,   342,   0,
		412,   32767, 490,   339,   373,   32767, 0,     -259,
		562,   546,   -306,  527,   32767, 0,     -57,   522,
		-370,  176,   641,   116,   32767, 226,   0,     32767,
		0,     129,   0,     32767, 38,    0,     -300,  428,
		32767, 32767, 529,   455,   32767, 0,     32767, 32767,
		32767, 478,   -230,  32767, -58,   573,   556,   32767,
		-278,  32767, 460,   32767, -31,   32767, 969,   32767,
		521,   0,     170,   -85,   321,   553,   0,     436,
		32767, 32767, 223,   -195,  32767, 32767, -24,   0,
		400,   0,     32767, 165,   32767, 157,   32767, 32767,
		350,   32767, 32767, 32767, 28,    32767, 32767, 0,
		332,   378,   32767, 32767, 32767, 134,   -90,   32767,
		32767, 613,   -2,    32767, 32767, 32767, 0,     -209,
		0,     439,   285,   32767, 345,   0,     32767, 0,
		584,   32767, 48,    32767, 131,   580,   922,   -204,
		32767, 32767, -109,  599,   173,   32767, 32767, 520,
		-123,  460,   104,   32767, 0,     32767, 269,   897,
		32767, 0,     254,   32767, 32767, 32767, 32767, 32767,
		-127,  32767, 32767, 421,   623,   32767, 275,   32767,
		345,   32767, 32767, 32767, 32767, 1251,  32767, -182,
		372,   32767, 964,   54,    32767, 687,   74,    311,
		32767, 0,     32767, 0,     32767, 435,   0,     32767,
		125,   32767, -334,  335,   223,   32767, 32767, 0,
		647,   32767, 1064,  -579,  486,   -137,  178,   163,
		32767, 32767, 694,   858,   529,   32767, 32767, 32767,
		329,   -93,   32767, 32767, -635,  1209,  139,   317,
		0,     454,   32767, 642,   -338,  32767, 660,   438,
		531,   32767, -50,   -233,  32767, 5,     -300,  253,
		177,   32767, 32767, 32767, 633,   32767, 32767, 0,
		32767, 645,   132,   338,   0,     592,   32767, 32767,
		-393,  0,     313,   -279,  32767, 32767, 384,   -153,
		117,   0,     32767, 0,     384,   32767, 602,   32767,
		0,     32767, 1494,  32767, 0,     -75,   32767, 559,
		32767, 393,   344,   91,    32767, 10,    32767, 22,
		861,   548,   32767, 461,   0,     32767, -1061, 32767,
		32767, 32767, 32767, 32767, 32767, 0,     702,   635,
		13,    32767, 0,     453,   32767, -84,   -132,  32767,
		32767, 0,     32767, 653,   168,   291,   32767, 0,
		32767, 0,     0,     32767, 261,   32767, 628,   32767,
		975,   32767, 413,   76,    -715,  930,   699,   32767,
		-615,  415,   -123,  32767, 0,     -409,  683,   32767,
		0,     456,   32767, 327,   0,     -106,  216,   141,
		32767, 403,   32767, 0,     682,   32767, 68,    -197,
		32767, -200,  0,     342,   409,   632,   -366,  0,
		32767, -346,  73,    32767, 32767, 0,     32767, 0,
		32767, 0,     32767, 110,   32767, 0,     -427,  0,
		32767, 0,     -329,  -127,  0,     -194,  0,     589,
		32767, 32767, 368,   32767, 155,   32767, 32767, 32767,
		325,   32767, 32767, 32767, 450,   -740,  32767, -29,
		212,   32767, 170,   15,    0,     858,   667,   105,
		0,     572,   0,     500,   788,   0,     0,     32767,
		168,   32767, 0,     57,    -377,  32767, 955,   307,
		0,     32767, 0,     -255,  32767, 0,     746,   32767,
		32767, 32767, -257,  206,   -366,  32767, 0,     0,
		32767, -106,  -66,   483,   32767, 32767, -153,  734,
		32767, 32767, 657,   32767, 646,   32767, 32767, 497,
		0,     0,     32767, 32767, 32767, 653,   795,   32767,
		-513,  32767, 32767, 0,     247,   80,    619,   32767,
		-347,  68,    32767, 32767, -731,  682,   32767, 32767,
		0,     32767, -114,  350,   0,     502,   79,    32767,
		0,     -684,  0,     0,     -70,   32767, 32767, 32767,
		32767, 0,     85,    321,   32767, 32767, 32767, 32767,
		32767, 0,     284,   0,     32767, 0,     0,     32767,
		32767, 32767, 98,    0,     32767, 32767, 119,   358,
		32767, -1165, 666,   308,   -134,  -24,   301,   497,
		32767, 243,   0,     0,     32767, 0,     32767, 32767,
		313,   32767, 775,   32767, 32767, 173,   32767, 0,
		32767, 511,   32767, 32767, 32767, 1670,  -246,  32767,
		32767, 339,   32767, 32767, -109,  32767, 411,   -19,
		32767, 495,   47,    32767, 72,    0,     32767, 34,
		114,   0,     32767, 32767, -483,  0,     0,     21,
		303,   -291,  32767, 32767, -273,  32767, 0,     -269,
		94,    292,   121,   32767, 477,   32767, 637,   32767,
		530,   214,   32767, 32767, 0,     577,   32767, 353,
		654,   -640,  362,   32767, 32767, 32767, 20,    -483,
		32767, 32767, 0,     32767, 0,     -113,  0,     32767,
		0,     0,     407,   32767, 32767, 0,     440,   32767,
		-357,  252,   32767, 32767, 32767, 32767, 434,   32767,
		32767, 360,   32767, 32767, 136,   77,    32767, 0,
		32767, 208,   612,   32767, 486,   32767, 0,     32767,
		313,   346,   54,    -173,  410,   0,     32767, -30,
		182,   32767, -1255, 58,    618,   0,     32767, 32767,
		32767, 32767, 32767, 151,   37,    607,   147,   420,
		32767, -218,  675,   123,   32767, 32767, -813,  32767,
		0,     32767, 0,     32767, 23,    369,   794,   32767,
		0,     0,     0,     680,   0,     -412,  32767, 32767,
		229,   331,   32767, 1047,  32767, -235,  0,     32767,
		32767, 130,   331,   0,     504,   493,   424,   0,
		0,     32767, -79,   32767, 0,     0,     32767, 32767,
		32767, -609,  0,     -441,  -178,  -776,  32767, 512,
		32767, 201,   32767, 0,     0,     193,   0,     32767,
		416,   743,   559,   692,   32767, 528,   32767, 548,
		32767, 32767, 451,   32767, -81,   0,     0,     32767,
		32767, 230,   536,   32767, 0,     32767, 0
	};

	const unsigned char *k = (const unsigned char *) key;
	uint32		a = 0;
	uint32		b = 1;

	while (keylen--)
	{
		unsigned char c = *k++ | 0x20;

		a = a * 257 + c;
		b = b * 127 + c;
	}
	return h[a % 1383] + h[b % 1383];
}

const ScanKeywordList ScanKeywords = {
	ScanKeywords_kw_string,
	ScanKeywords_kw_offsets,
	ScanKeywords_hash_func,
	SCANKEYWORDS_NUM_KEYWORDS,
	26
};

#endif							/* KWLIST_D_H */
